name: Validate Azure Configuration

on:
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest

    env:
      rg: ${{ vars.AZURE_RESOURCE_GROUP }}

    steps:
      - uses: actions/checkout@v4
      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: azure/cli@v2
        with:
          inlineScript: |
            az group show -n ${{ env.rg }}
